# -*- coding: utf-8 -*-
"""RetinaFace facial Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smNCdKTdZqS12xVKhFU1t1NmPo9o7lm0
"""

pip install retina-face

from retinaface import RetinaFace
 import matplotlib.pyplot as plt 
 import cv2

img_path = "/content/drive/MyDrive/face dataset/crowded.jpeg"

img = cv2.imread(img_path)

obj = RetinaFace.detect_faces(img_path)

len(obj.keys())

for i in obj.keys():
  identity = obj[i]

  facial_area = identity["facial_area"]
  cv2.rectangle(img ,(facial_area[2],facial_area[3]),(facial_area[0],facial_area[1]), (255,255,255) ,1)

plt.figure(figsize = (10,10))
plt.imshow(img[:,:,::-1])
plt.show()

